apiVersion: v1
kind: Service
metadata:
  name: leave-nginx-service
  namespace: tan-app
spec:
  selector:
    app: leave-nginx
  ports:
    - port: 8888
      targetPort: 80
      name: standard
  type: NodePort
